npm config delete chromedriver-cdnurl
npm config delete couchbase-binary-host-mirror
npm config delete debug-binary-host-mirror
npm config delete disturl
npm config delete electron-mirror
npm config delete flow-bin-binary-host-mirror
npm config delete fse-binary-host-mirror
npm config delete fuse-bindings-binary-host-mirror
npm config delete git4win-mirror
npm config delete gl-binary-host-mirror
npm config delete grpc-node-binary-host-mirror
npm config delete hackrf-binary-host-mirror
npm config delete leveldown-binary-host-mirror
npm config delete leveldown-hyper-binary-host-mirror
npm config delete mknod-binary-host-mirror
npm config delete node-sqlite3-binary-host-mirror
npm config delete node-tk5-binary-host-mirror
npm config delete nodegit-binary-host-mirror
npm config delete operadriver-cdnurl
npm config delete phantomjs-cdnurl
npm config delete profiler-binary-host-mirror
npm config delete puppeteer-download-host
npm config delete python-mirror
npm config delete rabin-binary-host-mirror
npm config delete sass-binary-site
npm config delete sodium-prebuilt-binary-host-mirror
npm config delete sqlite3-binary-site
npm config delete utf-8-validate-binary-host-mirror
npm config delete utp-native-binary-host-mirror
npm config delete zmq-prebuilt-binary-host-mirror